# Generated by Django 5.1.6 on 2025-02-19 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=50, unique=True)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nomor_whatsapp', models.CharField(max_length=15)),
                ('tinggi_badan', models.IntegerField(help_text='Tinggi badan dalam cm')),
                ('berat_badan', models.IntegerField(help_text='Berat badan dalam kg')),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('status_siswa', models.CharField(choices=[('AKTIF', 'Aktif'), ('ALUMNI', 'Alumni'), ('PINDAH', 'Pindah'), ('DIKELUARKAN', 'Dikeluarkan')], max_length=11)),
                ('status_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'db_table': 'siswa',
            },
        ),
    ]
