# Generated by Django 5.1.6 on 2025-02-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Dashboard.school', verbose_name='Sekolah'),
        ),
    ]
