# Generated by Django 5.1.6 on 2025-02-20 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_student_sekolah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('ALPA', 'Alpa')], max_length=50)),
                ('absen_type', models.CharField(choices=[('MASUK', 'Masuk'), ('PULANG', 'Pulang')], max_length=6)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Dashboard.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Dashboard.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'unique_together': {('date', 'student', 'sekolah', 'absen_type')},
            },
        ),
    ]
