# Generated by Django 5.1.6 on 2025-02-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_attendancepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermission',
            name='accept_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='document',
            field=models.FileField(blank=True, help_text='Upload dokumen pendukung (PDF/Image)', null=True, upload_to='permission_documents/'),
        ),
    ]
